include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - lib/graphql/graphql_api*.dart
    - lib/identification/protobuf/*.dart
  errors:
    missing_required_param: warning
    unused_import: error
    prefer_const_constructors: error
    require_trailing_commas: error

linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: true
