include: package:flutter_lints/flutter.yaml
#include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/graphql/graphql_api*.dart
    - lib/identification/protobuf/*.dart
  errors:
    missing_required_param: warning
    unused_import: error
    prefer_const_constructors: error
    require_trailing_commas: error
    prefer_final_locals: error
    prefer_const_declarations: error
    always_declare_return_types: error
    sort_child_properties_last: error
    directives_ordering: error
    prefer_if_elements_to_conditional_expressions: error
    prefer_final_in_for_each: error


linter:
  rules:
    avoid_redundant_argument_values: false
    require_trailing_commas: true
    prefer_final_locals: true
    prefer_const_declarations: true
    always_declare_return_types: true
    sort_child_properties_last: true
    directives_ordering: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_final_in_for_each: true
