include: package:flutter_lints/flutter.yaml
#include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/graphql/graphql_api*.dart
    - lib/identification/protobuf/*.dart
  errors:
    missing_required_param: warning
    unused_import: error
    prefer_const_constructors: error
    require_trailing_commas: error
    prefer_final_locals: error
    prefer_const_declarations: error
    always_declare_return_types: error

linter:
  rules:
    - require_trailing_commas
    - prefer_final_locals
    - prefer_const_declarations
    - always_declare_return_types
