# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    sources:
      - $package$
      - lib/$lib$
      - "**.graphql"
      - proto/**
      - lib/build_config/build_config.yaml
      - assets/l10n/*
    builders:
      df_build_config:
        generate_for:
          include:
            - "lib/build_config/build_config.yaml"
        enabled: True
      protoc_builder:
        options:
          use_installed_protoc: false
          protobuf_version: "27.5"
          use_protoc_plugin_from_pubspec: true
          root_dir: "proto/"
          proto_paths:
            - "proto/"
          out_dir: "lib/proto"
          grpc: false
          precompile_protoc_plugin: true
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          outputDirectory: /lib/graphql_gen/
          assetsPath: "**.graphql"
          scalars:
            Long:
              type: int
            Upload: # Not used in flutter frontend.
              type: String
      slang_build_runner:
        options:
          base_locale: de
          input_directory: assets/l10n
          input_file_pattern: .json
          output_file_name: translations.g.dart
          output_directory: lib/l10n
          translation_overrides: true
          string_interpolation: double_braces
