name: ehrenamtskarte
description: App for the Bavarian Ehrenamtskarte owners.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.5+106

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: 3.3.0

dependency_overrides:
  maplibre_gl_platform_interface:
    git:
      url: https://github.com/maxammann/flutter-maplibre-gl.git
      path: maplibre_gl_platform_interface
      ref: reenable-textureMode

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  maplibre_gl:
    git:
      url: https://github.com/maxammann/flutter-maplibre-gl.git
      ref: reenable-textureMode
  provider: ^6.0.3
  graphql_flutter: ^5.1.0
  url_launcher: ^6.1.6
  flutter_svg: ^1.1.4
  permission_handler: ^10.2.0
  package_info_plus: ^1.4.3+1 # for about dialog
  mobile_scanner: ^2.1.0
  flutter_secure_storage: ^6.0.0
  infinite_scroll_pagination: ^3.2.0
  geolocator: ^9.0.1
  mutex: ^3.0.0
  protobuf: ^2.1.0
  base32: ^2.1.3
  qr_flutter: ^4.0.0
  otp: ^3.1.1
  crypto: ^3.0.2
  intro_slider: ^3.0.10
  shared_preferences: ^2.0.15
  tinycolor2: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  collection: ^1.16.0
  meta: ^1.8.0
  http: ^0.13.5
  equatable: ^2.0.5
  tuple: ^2.0.0

dev_dependencies:
  build_runner: ^2.2.0
  df_protobuf:
    path: ./pubs/df_protobuf
  df_build_config:
    path: ./pubs/df_build_config
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  effective_dart: ^1.3.2
  test: '>=1.0.0'

  # graphQL type generation
  artemis: '>=6.0.0' # only if you're using ArtemisClient!
  json_annotation: ^4.6.0
  gql: '>=0.12.3 <1.0.0'
  lint: ^1.7.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/category_icons/
    - assets/detail_headers/
    - assets/bayern/intro_slides/
    - assets/bayern/header-logo.png
    - assets/bayern/body-logo.png
    - assets/bayern/icon.png
    - assets/nuernberg/header-logo.png
    - assets/nuernberg/body-logo.png
    - assets/nuernberg/background.png
    - assets/nuernberg/intro_slides/

  # An image asset can refer to one or more resolution-specific 'variants', see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this 'flutter' section. Each entry in this list should have a
  # 'family' key with the font family name, and a 'fonts' key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
