frontend_task_template: &FRONTEND_TASK_TEMPLATE
  container:
    image: cirrusci/flutter:latest
  pub_cache:
    folder: ~/.pub-cache
    reupload_on_changes: false # since there is a fingerprint script
    fingerprint_script:
      - echo $CIRRUS_OS
      - flutter --version
      - cat frontend/pubspec.yaml
    populate_script: 
      - cd frontend
      - flutter pub get
  environment:
    SECRETS_JSON: ENCRYPTED[c73df347c1def703d16419893945dfe6484e785569ac31fa720479de68addfd82070684f0006103fc34f890a6e2897e4]
  secrets_json_file:
    path: ~/frontend/secrets.json
    variable_name: SECRETS_JSON

lint_task:
  << : *FRONTEND_TASK_TEMPLATE
  lint_script:
    - cd frontend
    - ../scripts/enforceDartStyle.sh

test_task:
  << : *FRONTEND_TASK_TEMPLATE
  test_script:
    - cd frontend
    - flutter test
