version: "3.3"
services:
  backend:
    build: ./backend/
    environment:
      - BACKEND_OPTS=-Dapp.postgres.host=db-postgis -Dapp.postgres.user=postgres -Dapp.postgres.port=5432 -Dapp.postgres.password=postgres -Dapp.postgres.database=ehrenamtskarte
    depends_on:
      - db-postgis
    networks:
      - network
  martin:
    build: ./docker/martin
    volumes:
      - ./docker/martin/config.yaml:/app/config.yaml
    depends_on:
      - db-postgis
    networks:
      - network
  db-postgis:
    image:  postgis/postgis:13-3.0-alpine
    environment:
      - POSTGRES_DB=ehrenamtskarte
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - network
  adminer:
    image: "adminer:4.7.7-standalone"
    ports:
      - 127.0.0.1:5001:8080
    networks:
      - network
  reverse_proxy:
    image: "nginx:1.19.5"
    ports:
      - 127.0.0.1:5002:80
      - 127.0.0.1:5003:81
    volumes:
      - ./docker/reverse_proxy/www:/usr/share/nginx/html
      - ./docker/reverse_proxy/nginx-development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - martin
      - backend
    networks:
      - network
networks:
  network:
    name: network
