steps:
  - run:
      name: Install FVM
      command: |
        dart pub global activate fvm
        echo 'export PATH=$HOME/.pub-cache/bin:$PATH' >> $BASH_ENV
        export PATH="$PATH":"$HOME/.pub-cache/bin"
  - restore_cache:
      keys:
        - fvm-0-{{ checksum "frontend/.fvmrc" }}-{{ arch }}
  - run:
      name: Install Flutter
      command: fvm install
      working_directory: ~/project/frontend/
  - save_cache:
      key: fvm-0-{{ checksum "frontend/.fvmrc" }}-{{ arch }}
      paths:
        - .fvm
        - ~/fvm/
  - run:
      name: Show Flutter version
      command: fvm flutter --version
      working_directory: ~/project/frontend/
  - run:
      name: Configure Flutter
      command: fvm flutter config --no-analytics
      working_directory: ~/project/frontend/