description: Send a notification (to Mattermost) at the end of a job, based on success or failure. Must be the last step in a job.
parameters:
  success_message:
    default: ''
    type: string
  failure_mentions:
    default: '@stefanie.metzger @andreas.fischer'
    type: string
  success_mentions:
    default: ''
    type: string
  allow-all-branches:
    default: false
    type: boolean
  channel:
    default: @stefanie.metzger
    type: string
steps:
  - run:
      command: |
            echo 'export MM_MESSAGE=":fire: The [${CIRCLE_JOB}](${CIRCLE_BUILD_URL}) job has failed on the main branch! :fire:\n<< parameters.failure_mentions >>"' >> $BASH_ENV
      name: Mattermost - Prepare failure message
      when: on_fail
  - run:
      command: |
        if [ -n "<< parameters.success_message >>" ]; then
            echo 'export MM_MESSAGE="<< parameters.success_message >>"' >> $BASH_ENV
        fi
      name: Mattermost - Prepare success message
      when: on_success
  - run:
      command: |
        echo 'export set-allow-all-branches-flag=<<parameters.allow-all-branches>> || $CIRCLE_BRANCH == release*>>' 
        app-toolbelt v0 notify mattermost --message MM_MESSAGE --channel << parameters.channel >> ${set-allow-all-branches-flag:+--allow-all-branches}
      name: Mattermost Status Alert
      when: always
