when: << pipeline.parameters.run_commit >>
jobs:
  - bump_version:
        prepare_delivery: false
        context:
          - deliverino
  - check
  - build_backend
  - pack_backend:
      requires:
        - build_backend
        - bump_version
  - check_administration
  - check_health_backend:
      requires:
        - pack_backend
  - check_frontend