when: << pipeline.parameters.run_deliver_beta_backend_administration >>
jobs:
  - bump_version:
      prepare_delivery: false
      context:
        - deliverino
  - check_administration
  - build_administration:
      requires:
        - check_administration
        - bump_version
  - pack_administration:
      requires:
        - build_administration
  - build_martin
  - check_backend
  - build_backend:
      requires:
        - check_backend
  - pack_backend:
      requires:
        - build_backend
        - bump_version
  - check_health_backend:
      requires:
        - pack_backend
  - pack_martin:
      requires:
        - build_martin
        - bump_version
  - pack_meta:
      requires:
        - bump_version
  - deliver_to_server:
      name: deliver_administration_staging
      production: false
      bundle: administration
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_administration
        - check_health_backend
        - pack_martin
        - pack_meta
  - deliver_to_server:
      name: deliver_backend_staging
      production: false
      bundle: backend
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_administration
        - check_health_backend
        - pack_martin
        - pack_meta

