when: << pipeline.parameters.run_deliver_beta_administration >>
jobs:
  - bump_version:
        prepare_delivery: true
        context:
          - deliverino
  - check_administration
  - build_administration:
      requires:
        - check_administration
        - bump_version
  - pack_administration:
      requires:
        - build_administration
  - deliver_to_server:
      name: deliver_administration_staging
      production: false
      bundle: administration
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_administration

