when: << pipeline.parameters.run_deliver_production_backend >>
jobs:
  - bump_version:
      prepare_delivery: true
      context:
        - deliverino
  - build_backend
  - build_martin
  - pack_backend:
      requires:
        - build_backend
        - bump_version
  - check_health_backend:
      requires:
        - pack_backend
  - pack_martin:
      requires:
        - build_martin
        - bump_version
  - pack_meta:
      requires:
        - bump_version
  - deliver_backend:
      name: deliver_backend_production
      production: true
      context:
        - credentials-ehrenamtskarte
      requires:
        - pack_backend
        - check_health_backend
        - pack_martin
        - pack_meta

