version: 2.1
orbs:
  gradle: circleci/gradle@2.2.0
workflows:
  default:
    jobs:
      - check-frontend
      - frontend-android-build:
          requires:
            - check-frontend
      - frontend-ios-build:
          requires:
            - check-frontend
      - backend-build
      - administration-build
      - martin-build
      - backend-pack:
          requires:
            - backend-build
      - administration-pack:
          requires:
            - administration-build
      - martin-pack:
          requires:
            - martin-build
      - meta-pack
      - styles-pack
      - deploy:
          requires:
            - backend-pack
            - administration-pack
            - styles-pack
            - martin-pack
            - meta-pack
          filters:
            branches:
              only:
                - main

commands:
  install-dart-linux:
    steps:
      - run:
          name: Install Dart
          command: |
            wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/linux_packages/dart_2.15.0-1_amd64.deb
            sudo dpkg -i dart_2.15.0-1_amd64.deb
  install-fvm-linux:
    steps:
      - install-dart-linux
      - run:
          name: Install FVM
          command: |
            dart pub global activate fvm
            echo 'export PATH=$HOME/.pub-cache/bin:$PATH' >> $BASH_ENV
      - restore_cache:
          keys:
            - flutter-3-{{ checksum ".fvm/fvm_config.json" }}-{{ arch }}
      - run:
          name: Install Flutter
          command: |
            fvm --verbose install
      - save_cache:
          key: flutter-3-{{ checksum ".fvm/fvm_config.json" }}-{{ arch }}
          paths:
            - .fvm
            - ~/fvm/
      - run:
          name: Configure Flutter
          command: |
            fvm --verbose flutter config --no-analytics
  install-fvm-mac:
    steps:
      - run:
          name: Install Standalone FVM (with Dart)
          command: |
            brew tap leoafarias/fvm
            brew install fvm
      - restore_cache:
          keys:
            - flutter-3-{{ checksum ".fvm/fvm_config.json" }}-{{ arch }}
      - run:
          name: Install Flutter
          command: |
            fvm --verbose install
      - save_cache:
          key: flutter-3-{{ checksum ".fvm/fvm_config.json" }}-{{ arch }}
          paths:
            - .fvm
            - ~/fvm/
      - run:
          name: Configure Flutter
          command: |
            fvm --verbose flutter config --no-analytics

jobs:
  check-frontend:
    docker:
      - image: cimg/base:2020.01
    resource_class: small
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - install-fvm-linux
      - run:
          name: Check Formatting
          command: dart format -l 120 -o none --set-exit-if-changed .
      - run:
          name: Check Analyzer and Linting
          command: fvm flutter analyze --fatal-infos --fatal-warnings

  frontend-android-build:
    docker:
      - image: circleci/android:api-30
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m" -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2'
    resource_class: large
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - install-fvm-linux
      - restore_cache:
          keys:
            - pub-2-{{ checksum "pubspec.lock" }}-{{ arch }}
      - run:
          name: Install Flutter Packages
          command: |
            fvm flutter pub get
            fvm flutter precache --android
      - save_cache:
          key: pub-2-{{ checksum "pubspec.lock" }}-{{ arch }}
          paths:
            - .dart_tool
      - run:
          name: Build
          command: |
            fvm --verbose flutter build apk --release -t lib/main_prod.dart
      - store_artifacts:
          path: build/app/outputs/flutter-apk/


  frontend-ios-build:
    macos:
      xcode: 13.2.0
    working_directory: ~/project/frontend
    steps:
      - checkout:
          path: ~/project
      - install-fvm-mac
      - restore_cache:
          keys:
            - pub-2-{{ checksum "pubspec.lock" }}-{{ arch }}
      - run:
          name: Install Flutter Packages
          command: |
            fvm flutter pub get
            fvm flutter precache --ios
      - save_cache:
          key: pub-2-{{ checksum "pubspec.lock" }}-{{ arch }}
          paths:
            - .dart_tool
      - run:
          name: Update Pods
          command: |
            cd ios
            pod update # This command is somehow needed: https://github.com/m0nac0/flutter-maplibre-gl/pull/9
            pod install
      - run:
          name: Build
          command: |
            fvm --verbose flutter build ios --no-codesign --release -t lib/main_prod.dart

  backend-build:
    environment:
      _JAVA_OPTIONS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - restore_cache:
          key: v2-gradle-cache-{{ checksum "build.gradle.kts" }}
      - run: ./gradlew build
      - save_cache:
          paths:
            - .gradle/wrapper
          key: v2-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - .gradle/caches
          key: v2-gradle-cache-{{ checksum "build.gradle.kts" }}
      - store_artifacts:
          path: build/libs
      - persist_to_workspace:
          root: ~/project
          paths:
            - backend/build/distributions/*

  administration-build:
    docker:
      - image: cimg/node:15.8.0
    working_directory: ~/project/administration
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys:
            - v1-node-modules-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - run:
          name: Install node dependencies
          command: "[ ! -d node_modules ] && npm ci --loglevel warn --yes || echo package.json and package-lock.json unchanged. Using cache."
      - run: |
          npm run generate-graphql
          npm run generate-protobuf
          npm run-script build
      - save_cache:
          paths:
            - node_modules
          key: v1-node-modules-{{ checksum "package.json" }}-{{checksum "package-lock.json" }}
      - store_artifacts:
          path: build
      - persist_to_workspace:
          root: ~/project
          paths:
            - administration/build

  martin-build:
    docker:
      - image: rust:1.50.0
    working_directory: ~/martin
    steps:
      - run:
          name: "Checkout"
          command: |
            mkdir -p ~/.ssh
            touch ~/.ssh/known_hosts
            echo "github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" >> ~/.ssh/known_hosts
            git clone git@github.com:urbica/martin.git ~/martin
            git config advice.detachedHead false
            git checkout ed14582a8f5c3e11bfb165f3b012edccd929b479
      - restore_cache:
          keys:
            - v1-cargo-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: "Install OpenSSL"
          command: |
            apt update
            apt install -y openssl libssl-dev
      - run:
          name: "Build"
          command: |
            cargo build --release --target x86_64-unknown-linux-gnu
      - save_cache:
          paths:
            - "~/.cargo"
            - "target"
          key: v1-cargo-{{ checksum "Cargo.toml" }}-{{ checksum "Cargo.lock" }}
      - run:
          name: "Prepare storing"
          command: |
            mkdir -p /tmp/artifacts/martin
            cp target/x86_64-unknown-linux-gnu/release/martin /tmp/artifacts/martin
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - martin/martin

  backend-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: /tmp/workspace
      - run: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -t /tmp/workspace/backend/build/distributions/*.tar -s ~/project/scripts/eak-backend.service -d "Backend server for the Ehrenamtskarte app" -n "eak-backend" -c "default-jre"
      - run: |
          mkdir -p /tmp/artifacts/debs
          mv *.deb /tmp/artifacts/debs
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  administration-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/administration
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: /tmp/workspace
      - run: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -f /tmp/workspace/administration/build -d "Administration backend for the Ehrenamtskarte app" -n "eak-administration"
      - run: |
          mkdir -p /tmp/artifacts/debs
          mv *.deb /tmp/artifacts/debs
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  styles-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/map-tiles/styles
    steps:
      - checkout:
          path: ~/project
      - run:
          name: "Download legacy styles deb"
          command: wget https://github.com/digitalfabrik/ehrenamtskarte-maplibre-style/releases/download/before-migration/eak-map-styles_0.4785-1_all.deb
      - run:
          name: "Move .deb to artifacts folder"
          command: |
            mkdir -p /tmp/artifacts/debs
            mv *.deb /tmp/artifacts/debs
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  martin-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/map-tiles/martin
    steps:
      - checkout:
          path: ~/project
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: "Build .deb"
          command: |
            cp /tmp/workspace/martin/martin .
            ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -d "Martin tile server for the Ehrenamtskarte app" -n "eak-martin" -s ~/project/scripts/eak-martin.service -C "/opt/ehrenamtskarte/martin/config.yaml" -M .
      - run:
          name: "Move .deb to artifacts folder"
          command: |
            mkdir -p /tmp/artifacts/debs
            mv *.deb /tmp/artifacts/debs
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  meta-pack:
    docker:
      - image: cimg/base:2020.01
    working_directory: ~/project/administration
    steps:
      - checkout:
          path: ~/project
      - run: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -d "Meta package for the Ehrenamtskarte app" -n "eak" -c "eak-backend, eak-administration, eak-map-styles, eak-martin"
      - run: |
          mkdir -p /tmp/artifacts/debs
          cp *.deb /tmp/artifacts/debs
      - store_artifacts:
          path: /tmp/artifacts
      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - debs/*.deb

  deploy:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - add_ssh_keys:
          fingerprints:
            - "5c:8a:70:dc:61:9d:fa:c2:c2:6d:2d:fc:4a:ab:d2:e3"
      - run:
          name: "SFTP upload"
          command: |
            echo $APT_HOST_FINGERPRINT > known_hosts
            echo "Uploading: " /tmp/workspace/debs/*.deb
            sftp -b - -o UserKnownHostsFile=known_hosts ci@apt.ehrenamtskarte.app:/local-apt-repository/ \<<< "put -r /tmp/workspace/debs/*.deb"
