macos:
  xcode: 15.2.0
parameters:
  buildConfig:
    description: "Name of the build config to use"
    type: enum
    enum: ['bayern', 'bayern-floss', 'nuernberg']
  flutterFlavor:
    description: "Flutter Flavor to use"
    type: enum
    enum: ['Bayern', 'BayernFloss', 'Nuernberg']
steps:
  - checkout:
      path: ~/project
  - install_dart_mac
  - install_fvm
  - install_app_toolbelt
  - install_protobuf_mac
  - prepare_workspace
  - restore_environment_variables
  - restore_ruby_cache:
      directory: frontend/ios
  - run:
      name: Install Flutter Packages
      command: |
        fvm flutter pub get --enforce-lockfile
        fvm flutter precache --ios
      working_directory: frontend/
  - restore_pods
  - run:
      name: "Fix: Delete flutter cache"
      command: cd ~/fvm/versions/3.19.3/bin && rm -rf cache/ && cd ~/project/frontend/ios/
  - run:
      name: "Fix: Flutter doctor"
      command: fvm flutter doctor
      working_directory: frontend/ios
  - run:
      name: "Fix: Flutter doctor + clean"
      command: fvm flutter doctor && fvm flutter clean
      working_directory: frontend/ios
  - run:
      name: '[FL] Build'
      command: bundle exec fastlane ios build version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE} flavor:<< parameters.flutterFlavor >> build_config_name:<< parameters.buildConfig >>
      working_directory: frontend/ios
  - store_artifacts:
      path: ~/<< parameters.buildConfig >>.ipa
  - persist_to_workspace:
      root: ~/
      paths:
        - << parameters.buildConfig >>.ipa
  - notify