docker:
  - image: cimg/node:19.1.0
working_directory: ~/project
steps:
  - checkout:
      path: ~/project
  - install_dart_linux
  - install_protobuf_linux
  - install_app_toolbelt
  - prepare_workspace
  - restore_environment_variables
  - restore_npm_cache
  - run:
      name: Generate GraphQL
      command: npm run generate-graphql
      working_directory: ~/project/administration
  - run:
      name: Generate Protobuf
      command: npm run generate-protobuf
      working_directory: ~/project/administration
  - run:
      name: Build
      command: npm run build --version_name=2024.3.24
      working_directory: ~/project/administration
  - store_artifacts:
      path: ~/attached_workspace/build
  - persist_to_workspace:
      root: ~/project
      paths:
        - administration/build
#  - notify
