docker:
  - image: cimg/base:2023.03
  - image: postgis/postgis:13-3.0-alpine
    environment:
      - POSTGRES_DB=ehrenamtskarte
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
steps:
  - checkout:
      path: ~/project
  - attach_workspace:
      at: /tmp/workspace
  - run: apt update -y && apt install -y nodejs npm
  - install_app_toolbelt
  - run:
      name: Install Curl
      command: |
        sudo apt update
        sudo apt install curl -y
  - run:
      name: Install ca-certificates-java # workaround for current issue: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1030129
      command: sudo apt install ca-certificates-java
  - run:
      name: Install openjdk-17-jre-headless
      command: sudo apt install openjdk-17-jre-headless -y
  - run:
      name: Install backend
      command: sudo dpkg -i /tmp/workspace/debs/backend/eak-backend*.deb
  - run:
      name: Run migrate
      command: /opt/ehrenamtskarte/backend/bin/backend migrate
  - run:
      name: Start backend
      command: /opt/ehrenamtskarte/backend/bin/backend execute
      background: true
  - run:
      name: Check health
      command: curl --retry 120 --retry-delay 1 --retry-all-errors http://0.0.0.0:8000/health
  - notify