docker:
  - image: cimg/node:20.18.0-browsers
resource_class: small
environment:
  TOTAL_CPUS: 1 # For resource_class small
  TZ: 'Europe/Berlin' # Should be removed in IGAPP-39
shell: /bin/bash -eo pipefail
steps:
  - checkout:
      path: ~/project
  - install_app_toolbelt
  - check_circleci_config
  - notify