docker:
  - image: cimg/node:19.1.0-browsers
resource_class: small
environment:
  TOTAL_CPUS: 1 # For resource_class small
  TZ: 'Europe/Berlin' # Should be removed in IGAPP-39
shell: /bin/bash -eo pipefail
steps:
  - checkout
  - install_app_toolbelt
  - run:
      name: error
      command: npm run lint1
  - check_circleci_config
  - notify:
      allow-all-branches: true