# Deliver the app to the Google Play Store.
parameters:
  buildConfig:
    type: enum
    enum: ['bayern', 'bayern-floss', 'nuernberg']
  production_delivery:
    description: Whether to deliver the build to production.
    type: boolean
docker:
  - image: cimg/android:2023.02.1-node
resource_class: small
shell: /bin/bash -eo pipefail
environment:
  FASTLANE_SKIP_UPDATE_CHECK: true
steps:
  - checkout:
      path: ~/project
  - prepare_workspace
  - restore_ruby_cache:
      directory: ~/project/frontend/android
  - install_app_toolbelt
  - restore_environment_variables
  - run:
      name: '[FL] Play Store Upload'
      command: bundle exec fastlane android upload_to_playstore build_config_name:<< parameters.buildConfig >> production_delivery:"<< parameters.production_delivery >>" version_name:${NEW_VERSION_NAME} version_code:${NEW_VERSION_CODE}
      working_directory: ~/project/frontend/android
  - notify