docker:
  - image: cimg/base:2022.09
parameters:
  server:
    enum:
      - entitlementcard.tuerantuer.org
      - entitlementcard-test.tuerantuer.org
    type: enum
  ssh-host-fingerprint:
    enum:
      - '|1|dkYQrdGB1QML0o+POL3QzAkBbek=|b4Tm0Ymh82UKyZPJfVKy4t+MFV8= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIONuARu18Fktz+j4QosI+nRqgMnFOMgE7OZLuTOwgZ0k'
      - '|1|iikuvSrIo3wkj+EqUgLRMsAq6yk=|r9bSjkawWFa94b45qE/se5Oio5k= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIED3MwobbCs+ENMLXdyqlJb3bJ26TuIYt977TA3NrN66'
    type: enum
steps:
  - attach_workspace:
      at: /tmp/workspace
  - install_app_toolbelt
  - add_ssh_keys:
      fingerprints:
        - "a1:3f:a7:c3:ff:12:40:1d:85:de:a7:ab:12:3f:cc:05"
  - run:
      name: "SFTP upload"
      command: |
        echo "<< parameters.ssh-host-fingerprint >>" >> known_hosts
        echo "Uploading: " /tmp/workspace/debs/*.deb
        sftp -b - -o UserKnownHostsFile=known_hosts ci@<< parameters.server >>:/local-apt-repository/ \<<< "put -r /tmp/workspace/debs/*.deb"
  - notify