docker:
  - image: debian:11 # We deploy on debian -> pack on debian
working_directory: ~/project/administration
steps:
  - checkout:
      path: ~/project
  - attach_workspace:
      at: /tmp/workspace
  - prepare_workspace
  - restore_environment_variables
  - run: ~/project/scripts/pack_deb.sh -v "${NEW_VERSION_NAME}" -f /tmp/workspace/administration/build -d "Administration backend for the Ehrenamtskarte app" -n "eak-administration"
  - run: |
      mkdir -p /tmp/artifacts/debs/administration
      mv *.deb /tmp/artifacts/debs/administration
  - store_artifacts:
      path: /tmp/artifacts
  - persist_to_workspace:
      root: /tmp/artifacts
      paths:
        - debs/administration/*.deb