docker:
  - image: debian:11 # We deploy on debian -> pack on debian
working_directory: ~/project/backend
steps:
  - checkout:
      path: ~/project
  - attach_workspace:
      at: /tmp/workspace
  - prepare_workspace
  - restore_environment_variables
  - run: ~/project/scripts/pack_deb.sh -v "${NEW_VERSION_NAME}" -t /tmp/workspace/backend/build/distributions/*.tar -s ~/project/scripts/eak-backend.service -d "Backend server for the Ehrenamtskarte app" -n "eak-backend" -c "openjdk-17-jre-headless"
  - run: |
      mkdir -p /tmp/artifacts/debs/backend
      mv *.deb /tmp/artifacts/debs/backend
  - store_artifacts:
      path: /tmp/artifacts
  - persist_to_workspace:
      root: /tmp/artifacts
      paths:
        - debs/backend/*.deb