docker:
  - image: debian:11 # We deploy on debian -> pack on debian
working_directory: ~/project/administration
steps:
  - checkout:
      path: ~/project
  - prepare_workspace
  - restore_environment_variables
  - run: ~/project/scripts/pack_deb.sh -v "${NEW_VERSION_NAME}" -d "Meta package for the Ehrenamtskarte app" -n "eak" -c "eak-backend, eak-administration, eak-martin"
  - run: |
      mkdir -p ~/attached_workspace/debs/backend
      cp *.deb ~/attached_workspace/debs/backend
  - store_artifacts:
      path: ~/attached_workspace
  - persist_to_workspace:
      root: ~/attached_workspace
      paths:
        - debs/backend/*.deb
