docker:
  - image: debian:11 # We deploy on debian -> pack on debian
working_directory: ~/project/map-tiles/martin
steps:
  - checkout:
      path: ~/project
  - attach_workspace:
      at: /tmp/workspace
  - prepare_workspace
  - restore_environment_variables
  - run:
      name: "Build .deb"
      command: |
        cp ~/project/docker/martin-config.yaml config.yaml
        cp /tmp/workspace/martin/martin .
        ~/project/scripts/pack_deb.sh -v "${NEW_VERSION_NAME}" -d "Martin tile server for the Ehrenamtskarte app" -n "eak-martin" -s ~/project/scripts/eak-martin.service -C "/opt/ehrenamtskarte/martin/config.yaml" -M .
  - run:
      name: "Move .deb to artifacts folder"
      command: |
        mkdir -p /tmp/artifacts/debs
        mv *.deb /tmp/artifacts/debs
  - store_artifacts:
      path: /tmp/artifacts
  - persist_to_workspace:
      root: /tmp/artifacts
      paths:
        - debs/*.deb