docker:
  - image: debian:11 # We deploy on debian -> pack on debian
working_directory: ~/project/administration
steps:
  - checkout:
      path: ~/project
  - prepare_workspace
  - restore_environment_variables
  - run: ~/project/scripts/pack_deb.sh -v "${NEW_VERSION_NAME}" -d "Meta package for the Ehrenamtskarte app" -n "eak" -c "eak-backend, eak-administration, eak-martin"
  - run: |
      mkdir -p /tmp/artifacts/debs
      cp *.deb /tmp/artifacts/debs
  - store_artifacts:
      path: /tmp/artifacts
  - persist_to_workspace:
      root: /tmp/artifacts
      paths:
        - debs/*.deb