docker:
  - image: debian:11 # We deploy on debian -> pack on debian
working_directory: ~/project/map-tiles/martin
steps:
  - checkout:
      path: ~/project
  - prepare_workspace
  - restore_environment_variables
  - run:
      name: "Build .deb"
      command: |
        cp ~/project/docker/martin-config.yaml config.yaml
        cp ~/attached_workspace/martin/martin .
        ~/project/scripts/pack_deb.sh -v "${NEW_VERSION_NAME}" -d "Martin tile server for the Ehrenamtskarte app" -n "eak-martin" -s ~/project/scripts/eak-martin.service -C "/opt/ehrenamtskarte/martin/config.yaml" -M .
  - run:
      name: "Move .deb to artifacts folder"
      command: |
        mkdir -p ~/attached_workspace/debs/backend
        mv *.deb ~/attached_workspace/debs/backend
  - store_artifacts:
      path: ~/attached_workspace
  - persist_to_workspace:
      root: ~/attached_workspace
      paths:
        - debs/backend/*.deb
  - notify
