docker:
  - image: debian:11 # We deploy on debian -> pack on debian
steps:
  - checkout:
      path: ~/project
  - run: apt update -y && apt install -y nodejs npm
  - install_app_toolbelt
  - prepare_workspace
  - restore_environment_variables
  - run: ~/project/scripts/pack_deb.sh -v "2024.3.24" -f ~/attached_workspace/administration/build -d "Administration backend for the Ehrenamtskarte app" -n "eak-administration"
  - install_app_toolbelt
  - run: |
      mkdir -p ~/attached_workspace/debs/administration
      mv *.deb ~/attached_workspace/debs/administration
  - store_artifacts:
      path: ~/attached_workspace
  - persist_to_workspace:
      root: ~/attached_workspace
      paths:
        - debs/administration/*.deb
#  - notify