docker:
  - image: debian:11 # We deploy on debian -> pack on debian
working_directory: ~/project/backend
steps:
  - checkout:
      path: ~/project
  - attach_workspace:
      at: /tmp/workspace
  - run: apt update -y && apt install -y nodejs npm
  - install_app_toolbelt
  - run: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -t /tmp/workspace/backend/build/distributions/*.tar -s ~/project/scripts/eak-backend.service -d "Backend server for the Ehrenamtskarte app" -n "eak-backend" -c "openjdk-17-jre-headless"
  - run: |
      mkdir -p /tmp/artifacts/debs
      mv *.deb /tmp/artifacts/debs
  - store_artifacts:
      path: /tmp/artifacts
  - persist_to_workspace:
      root: /tmp/artifacts
      paths:
        - debs/*.deb
  - notify