docker:
  - image: debian:11 # We deploy on debian -> pack on debian
working_directory: ~/project/administration
steps:
  - checkout:
      path: ~/project
  - run: apt update -y && apt install -y nodejs npm
  - install_app_toolbelt
  - run: ~/project/scripts/pack_deb.sh -v "0.$CIRCLE_BUILD_NUM" -d "Meta package for the Ehrenamtskarte app" -n "eak" -c "eak-backend, eak-administration, eak-martin"
  - run: |
      mkdir -p /tmp/artifacts/debs
      cp *.deb /tmp/artifacts/debs
  - store_artifacts:
      path: /tmp/artifacts
  - persist_to_workspace:
      root: /tmp/artifacts
      paths:
        - debs/*.deb
  - notify