# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  # name of the builder
  df_protobuf:
    # library URI containing the builder
    import: "package:df_protobuf/builder.dart"
    # Name of the function in the above library to call.
    builder_factories: ["protobufBuilder"]
    # The mapping from the source extension to the generated file extension
    build_extensions: {".proto": [".dart"]}
    auto_apply: root_package
    # We would have liked to use "cache" here so we do not need to git-ignore the output of this builder.
    # Using "cache" is blocked by this issue: https://github.com/flutter/flutter/issues/91214
    build_to: source
    applies_builders: []

