name: df_protobuf
description: Generates protobufs required for the frontend
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  path: ^1.8.2
  build: ^2.0.0
  test: '>=1.0.0'
  lint: ^1.7.2
